services:
  model-manual: 
    build:
      context: model 
      target: builder
    stop_signal: "SIGINT"
  scheduler:
    build:
      context: scheduler
      target: builder
    secrets:
      - db-password
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - APP_REPLICA_IMAGE=docker.io/library/serverless-model-example-model-manual
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  test_scheduler:
    build:
      context: scheduler
      dockerfile: Dockerfile.test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - APP_REPLICA_IMAGE=docker.io/library/serverless-model-example-model-manual
volumes:
  db-data:
secrets:
  db-password:
    file: password.txt
