services:
  model-manual: 
    build:
      context: model 
      target: builder
    stop_signal: "SIGINT"
  scheduler:
    build:
      context: scheduler
      target: builder
    ports:
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - scheduler-state:/state
    environment:
      - APP_REPLICA_IMAGE=docker.io/library/serverless-model-example-model-manual
      - MODEL_SETUP_TIME=10
      - MODEL_PREDICT_TIME=3
      - STATE_FILE=/state/jobs.gob
  test_scheduler:
    build:
      context: scheduler
      dockerfile: Dockerfile.test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - APP_REPLICA_IMAGE=docker.io/library/serverless-model-example-model-manual
      - MODEL_SETUP_TIME=10
      - MODEL_PREDICT_TIME=3
volumes:
  scheduler-state:

